version: '3.9'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: okanban
      POSTGRES_PASSWORD: okanban
      POSTGRES_DB: okanban
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./data:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"  
  app:
    image: node:14
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    environment:
      - PG_URL=postgres://okanban:okanban@db:5432/okanban
      - PORT=3000
    depends_on:
      - db
    command: sh -c "npm install && npm start"

volumes:
  db-data:
