-- Generated by Mocodo 4.2.4

CREATE TABLE AFFECTE (
  PRIMARY KEY (code_carte, code_label),
  code_carte VARCHAR(42) NOT NULL,
  code_label VARCHAR(42) NOT NULL
);

CREATE TABLE AFFECTE_ROLE (
  PRIMARY KEY (code_utilisateur, code_role),
  code_utilisateur VARCHAR(42) NOT NULL,
  code_role        VARCHAR(42) NOT NULL
);

CREATE TABLE CARTE (
  PRIMARY KEY (code_carte),
  code_carte VARCHAR(42) NOT NULL,
  titre      VARCHAR(42),
  ordre      VARCHAR(42),
  couleur    VARCHAR(42),
  code_liste VARCHAR(42) NOT NULL
);

CREATE TABLE LABEL (
  PRIMARY KEY (code_label),
  code_label VARCHAR(42) NOT NULL,
  nom        VARCHAR(42),
  couleur    VARCHAR(42)
);

CREATE TABLE LISTE (
  PRIMARY KEY (code_liste),
  code_liste VARCHAR(42) NOT NULL,
  nom        VARCHAR(42),
  ordre      VARCHAR(42)
);

CREATE TABLE POSSEDE (
  PRIMARY KEY (code_utilisateur, code_liste),
  code_utilisateur VARCHAR(42) NOT NULL,
  code_liste       VARCHAR(42) NOT NULL
);

CREATE TABLE ROLE (
  PRIMARY KEY (code_role),
  code_role VARCHAR(42) NOT NULL,
  role      VARCHAR(42)
);

CREATE TABLE UTILISATEUR (
  PRIMARY KEY (code_utilisateur),
  code_utilisateur VARCHAR(42) NOT NULL,
  Nom              VARCHAR(42),
  Email            VARCHAR(42),
  Mot_De_Passe     VARCHAR(42)
);

ALTER TABLE AFFECTE ADD FOREIGN KEY (code_label) REFERENCES LABEL (code_label);
ALTER TABLE AFFECTE ADD FOREIGN KEY (code_carte) REFERENCES CARTE (code_carte);
ALTER TABLE AFFECTE_ROLE ADD FOREIGN KEY (code_role) REFERENCES ROLE (code_role);
ALTER TABLE AFFECTE_ROLE ADD FOREIGN KEY (code_utilisateur) REFERENCES UTILISATEUR (code_utilisateur);

ALTER TABLE CARTE ADD FOREIGN KEY (code_liste) REFERENCES LISTE (code_liste);

ALTER TABLE POSSEDE ADD FOREIGN KEY (code_liste) REFERENCES LISTE (code_liste);
ALTER TABLE POSSEDE ADD FOREIGN KEY (code_utilisateur) REFERENCES UTILISATEUR (code_utilisateur);
